---
- name: "configuration configure server."
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - record_host_keys: False

  roles:
    - configure-prometheus-node-exporter
