---
- name: "Extract backend artifact"
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: home/ubuntu

- name: "run app"
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop all
    pm2 start npm -- start