---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
- name: install dependencies
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "Extract artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu
    
- name: "start server"
  become: true
  shell: |
    npm install
    pm2 stop default
    sudo pm2 start npm --start