---
- name: "ensure backend dir exists"
  ansible.builtin.file:
    path: /home/ubuntu/backend
    state: directory

- name: "unarchive artifacts"
  become: true
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "add environment variables to the remote shell"
  become: true
  ansible.builtin.lineinfile:
    dest: "/home/ubuntu/backend/.env"
    regexp: "^{{ item.key }}="
    state: present
    line: "{{ item.key }}={{ item.value}}"
    create: yes
  with_items: "{{ os_environment }}"

- name: "start the server"
  ansible.builtin.shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start