# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core



trigger:
  - master

pool:
  vmImage: 'windows-latest'
  
name: '$(major).$(minor).$(revision)'


variables:
  buildConfiguration: 'Release'
  buildPlatform: 'AnyCPU'
  solution: 'src/afone.servicemanager.api/afone.servicemanager.api.csproj'
  selectOrConfig: 'config'
  major: '2'
  minor: '0'
  revision: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]
  nugetVersion: '$(major).$(minor).$(revision)'
  # NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS: 30
  # NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS: 30

steps:

#Restore
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    
- task: NuGetAuthenticate@0  

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '073cf11d-4641-4f5e-b87a-16af9d28c6f6/a20698c3-bc34-4a9e-ab5e-652bf3f5002c'



#Build project
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    feedsToUse: select
    vstsFeed: '073cf11d-4641-4f5e-b87a-16af9d28c6f6/a20698c3-bc34-4a9e-ab5e-652bf3f5002c'


#Publish project
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: false
    

#pack   
- task: NuGetCommand@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: 'src/afone.servicemanager.api/afone.servicemanager.api.nuspec'
    versionEnvVar: 'nugetVersion'
    versioningScheme: 'byEnvVar'




#Nuget Push
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '205c30f1-6e00-4967-939e-822492a0716d'
    allowPackageConflicts: true